
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/HcalCalibDetId",
  "LCGReflex/HcalCastorDetId",
  "LCGReflex/HcalDcsDetId",
  "LCGReflex/HcalDetId",
  "LCGReflex/HcalZDCDetId",
  "LCGReflex/CastorElectronicsId",
  "LCGReflex/HcalElectronicsId",
  "LCGReflex/HcalTrigTowerDetId",
  "LCGReflex/HcalOtherDetId",
  "LCGReflex/HcalFrontEndId",
  "LCGReflex/std::vector<CastorElectronicsId>",
  "LCGReflex/std::vector<HcalFrontEndId>",
  "LCGReflex/std::vector<HcalElectronicsId>",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

